- name: Create Token to join other nodes
  shell: kubeadm token create --print-join-command
  # save the outputtt in register
  register: created_token

- name: copy the token
  content: "{{ created_token.stdout  }}"
  dest: /tmp/join_token.sh
