- name: Initialize Kubeadm
  shell: |
    sudo kubeadm init --apiserver-advertise-address="{{ master_server_ip }}" --pod-network-cidr="{{ pod_network_cidr }}" --ignore-preflight-errors=Mem --ignore-preflight-errors=NumCPU --cri-socket /var/run/crio/crio.sock

    exit 0
  register: k8S_init_cluster

# Documentation:-  To start using your cluster, you need to run the following as a regular user:

- name: Create Kube Directory for Configuration
  include_tasks: kube-config-dir.yml 
  run_once: yes

- name: Joining Nodes
  include_tasks: joining-nodes.yml
  run_once: yes
